fix: sw in dev mode
r-k-t-a/starter pull request #34
Opened 2020-05-28 09:30 UTC by plusbpm

https://app.clubhouse.io/sdlk/story/480/fix-sw-config

2020-05-28 14:33 UTC, droganov requested changes

2020-05-28 14:33 UTC, droganov commented on public/sw_unregister.js
> +self.addEventListener("activate", function(e) {
пример того как твой преттиер не отработал на сохранении, разберись, устрани

2020-05-29 05:50 UTC, plusbpm commented on public/sw_unregister.js
> +self.addEventListener("activate", function(e) {
поправил

2020-05-31 19:50 UTC, droganov approved these changes

2020-05-31 19:50 UTC, merged